### ISSUE TITLE
New Module Loader?

### ISSUE THREAD

**Issue by weagle08** [dumberjs/dumber#10]
Just a question about a new module loader. I've grown to really like SystemJS because of it's ability to load modules no matter the output format, AMD, EJS etc. Why the decision to create yet another module loader? Were there limitations with a loader like SystemJS that the dumber module loader solves that the others do not?

**Comment by 3cp** [comment]
Nodejs compatibility.

For example, systemjs treat `some.js` and `some` as two separate module ids, requirejs has an option to normalize them. But both of them do not resolve module in nodejs compatible way, for example, `foo` can resolve to `foo/index` in nodejs.

Another annoying problem is ~~nodejs~~ commonjs supports circular dependency, that prevents systemjs/requirejs to load some tricky npm packages.

dumber-module-loader solved those issues. Read more here if you need some details https://github.com/dumberjs/dumber-module-loader

The new loader also made requirejs.config dynamic, you can call it again and again at runtime to add new bundle files. That's how it enabled runtime app composition https://github.com/dumberjs/examples/tree/master/runtime-composition-aurelia
