### ISSUE TITLE
Errors when using third-party libraries

### ISSUE THREAD

**Issue by developer-pta** [dumberjs/dumber#25]
Hi, I have created aurelia-typescript-dumber project using dumber.
No I want to use ie. toastr or iziToast to display toast messages.
With import like this:
`import toastr from "toastr";`
I get error: `app.ts:17 Uncaught (in promise) TypeError: Cannot read property 'info' of undefined`.

With import like this:
`import * as toastr from "toastr";`
I get error: `Uncaught (in promise) TypeError: toastr.info is not a function`

The usage pattern is: `toastr.info("Test");`

The same is for iziToast.
How to use toastr or iziToast with dumber and typescript?

**Comment by 3cp** [comment]
Dumber doesn't care about ts, it only consumes the compiled code from TypeScript. It's some TypeScript config issue likely. I will try the lib when I got time after work.

**Comment by developer-pta** [comment]
I even tried this:
`import {default as toastr} from "toastr";`
which gave me error:  Uncaught (in promise) TypeError: Cannot read property 'info' of undefined.

Setting "esModuleInterop" to false and using `import * as toastr from "toastr"` didn't solve the problem.

Trying to add desps in gulp.js like this:
` deps: [
      {name:'toastr', deps:["jquery"]}
  ],`
or
` deps: [
     'toastr'
  ],`
dint help neither.

**Comment by 3cp** [comment]
Too bad, it's compatibility issue in dumber bundler indeed.

Toastr has a special UMD wrapper which passes AMD define method as a param. This is different from other widely used UMD wrapper.

I will find a way to fix dumber bundler.

Note other bundlers (e.g. webpack) have no issue because they are not AMD environment. They just treat toastr as CommonJS module.

**Comment by 3cp** [comment]
I will ship the fix in 2 or 3 days.

**Comment by developer-pta** [comment]
Ok, thanks

**Comment by 3cp** [comment]
Clean up node_module and package-lock.json, then reinstall deps again. You should get the latest dumber and dumber-module-loader.

**Comment by developer-pta** [comment]
It works now thanks.
