### ISSUE TITLE
Struggling to import some libraries

### ISSUE THREAD

**Issue by luka-cetina** [dumberjs/dumber#26]
Hi, I have problems when I try to import some 3rd party libraries...
Like ie.:  [element-resize-detector](https://www.npmjs.com/package/element-resize-detector)
So , in Aurelia 1 application, I do:
`import * as erd from 'element-resize-detector';`
and when I try to use erd, it throws that erd is not a function.

But if I instead use this:
`let erd = require("element-resize-detector");`
it works.

**Comment by 3cp** [comment]
That lib is a traditional commonjs module, ~~normally we should able to use either `import * as erd` or default import `import erd` to use it.~~
~~But it looks like some kind of breaking change in latest babel helper.~~

Now you have to do `import erd from 'element-resize-detector';`. For now, you can simply fix it with this. I will read more to see if I can understand why babel behaviour changed.

When importing `* as erd`, babel wrap the real commonjs exports behind an esm default export `{ default: YourErdFunc }`.

**Comment by 3cp** [comment]
Might be my false memory. Babel might be doing this very long. It tries to make commonjs module as ESM module, hence when you do namespace import, it synthesises the default export for you.

**Comment by luka-cetina** [comment]
`import erd from 'element-resize-detector';` works. Man, they have complicated those jscript modules.
Thanks

**Comment by 3cp** [comment]
Closed as it's not in the control of dumber bundler.
