### ISSUE TITLE
Trouble with aurelia-bootstrapper when migrating Aurelia 1 app to use dumber

### ISSUE THREAD

**Issue by deap82** [dumberjs/dumber#28]
I'm trying to replace system.js/jspm in an Aurelia 1 app with dumber.
I made a parallell project using "npx makes dumber" (https://dumber.js.org/migrate-from-aurelia-cli) and have then hand-picked the stuff I need over to my existing code base.
For now I'm focusing on the compilation and bundling of .ts + .html files, so no css/scss involved right now.

I've come so far that my bundling task runs successfully but at runtime aurelia-bootstrapper.js is trying to be accessed at the root of my application (instead of in my "dist" folder). 

I tried looking at the parallell project created by "npx makes dumber" but can only find "aurelia-bootstrapper" in the package.json file and in the data-main attribute of the script tag referencing the entry-bundle in _index.html.
When the build task is run I can clearly see that "aurelia-bootstrapper" is part of the process, but I can not understand how dumber knows that it should be included? Is it aurelia-deps-finder that finds it due to that attribute in the html file? In my case the script entry tag is within a ".cshtml" file within a .net mvc site and not part of html files being bundled, so perhaps that's the reason. (In short, my architecture is an "asp.net mvc razor first" approach coupled with aurelia routing that is set up to request the mvc end points which returns html that is then "aurelia enhanced".)

I managed to solve _that_ runtime error by adding 'aurelia-bootstrapper' to the "deps" option of dumber, but then the runtime error is that "aurelia-loader-default.js" is not found within my dist folder. I cannot see any traces of "aurelia-loader-default" in the app created from "npx makes dumber". Should I have it?

I tried to add it and then it goes on to throw runtime errors for additional libraries, one at a time as I'm adding them in; 'aurelia-pal-browser', 'aurelia-logging-console', 'aurelia-templating-binding'.

At 'aurelia-templating-binding' I decided to stop and ask this question, because it feels like I'm doing something wrong... Some of these packages I didn't even have in my project before.
Any input appreciated, please let me know if you need more info, my hope is that the information I can provide will be something meaningful for anyone with some aurelia experience and involved in developing dumber.

(Creating a standalone reproduction of the issue will probably be difficult, but I'd be happy to schedule a screen share, showcasing/reviewing my code base, if anynone would be open to that.)

**Comment by 3cp** [comment]
Yes, it's aurelia-deps-finder. It doesn't pick it from _index.html.

It sounds like the aurelia-deps-finder didn't understand your src/main.ts, so it didn't add aurelia-bootstrapper (plus aurelia-loader-default and few others).

Can you share your src/main.ts file?

**Comment by 3cp** [comment]
FYI
https://github.com/dumberjs/aurelia-deps-finder/blob/c53146041a3681bce7bc95ed1cdb068a47f665f3/index.js#L123-L148

**Comment by deap82** [comment]
Thanks @3cp, looking at the code for aurelia-deps-finder led me in the right direction.

My main.ts calls into another module (shared between a few apps) that does most of the work normally done in main.ts. I was able to rearrange that module so that aurelia-deps-finder regards it as the "AureliaMainFile" 👍.

Just out of curiosity, what is the purpose of `data-main="aurelia-bootstrapper"` on the script tag that includes the entry bundle?

**Comment by 3cp** [comment]
It's requirejs way for the starting module. Aurelia v1 is special, the app's main file is loaded by aurelia-bootstrapper.

https://dumber.js.org/bundler-overview#no-main-aka-entry-module
