### ISSUE TITLE
Idea: Extract module directory prefixes for reduced bundle size

### ISSUE THREAD

**Issue by m-gallesio** [dumberjs/dumber#32]
Please regard this as just an idea / consideration.

The entry bundle contains a configuration which maps single modules to their containing bundle, like in this example:

```javascript
requirejs.config({
    // ...
    "bundles": {
        "myBundle": {
            "user": [
                "viewmodels/shared/account/signup.js",
                "viewmodels/shared/account/login.js",
                "viewmodels/shared/account/settings.js",
                "viewmodels/shared/account/recoverPassword.js",
                "viewmodels/shared/account/changePassword.js",
                // ...
            ],
            "package": [
                "jquery",
                "bootstrap"
            ]
        }
    }
}
```

As the full paths of files are included, this can lead to a somewhat large entry-bundle.

I think it might be worthwile to try to extract common path prefixes into constants.
For example, the previous code would become something like this:

```javascript
const ap = "viewmodels/shared/account/" // ap = Account Prefix
requirejs.config({
    // ...
    "bundles": {
        "myBundle": {
            "user": [
                ap + "signup.js",
                ap + "login.js",
                ap + "settings.js",
                ap + "recoverPassword.js",
                ap + "changePassword.js",
                // ...
            ],
            "package": [
                "jquery",
                "bootstrap"
            ]
        }
    }
}
```

This could notably reduce the size of entry-bundle, if the prefix names are short enough.

I can however see various problems with this approach:
- the prefix names would have to be gauranteed to be unique and designed in a way which ensures they are shorter than the actual prefix
- having to store the prefixes in constants and concatenate string at runtime might worsen performance (though I assume not by a noticeable amount)

Ultimately this might be more trouble than it is worth, but I wanted no note it nonetheless.

**Comment by 3cp** [comment]
I think various http supported compress format like gzip is a more generic solution :-)

The proposed solution is interesting, but bit difficult to implement as you recognised. The reason you have this problem is that you use many deep folders to organise your files. But other programmer may use less folder structures.

**Comment by m-gallesio** [comment]
Of couse I had forgotten compression.
Feel free to disregard this.
