### ISSUE TITLE
Yarn and npx makes dumberjs

### ISSUE THREAD

**Issue by simonfox** [dumberjs/dumber#33]
Sorry, not sure this is the right repo for this question...

New dumberjs project with makes is currently not working...
![image](https://github.com/dumberjs/dumber/assets/186663/b98af380-abaf-4037-88e6-d6a6b78ea8b2)

I'm assuming this is expected to work with Yarn2 as the `.yarnrc.yml` file includes Yarn2 configuration keys.

Try `yarn start`
![image](https://github.com/dumberjs/dumber/assets/186663/d8b86df9-341d-4099-bdc6-d256e4adfb81)

Try `npm start`
![image](https://github.com/dumberjs/dumber/assets/186663/2187ed56-5143-4369-aafe-ee1c4cd66dcf)

**Comment by simonfox** [comment]
![image](https://github.com/dumberjs/dumber/assets/186663/15ce770f-fdd9-446c-9238-9d4bb9e516a6)

![image](https://github.com/dumberjs/dumber/assets/186663/63161d78-f61b-4efb-b992-ecdb22470be9)

**Comment by 3cp** [comment]
Thx for the reporting!

Never tested dumber with yarn pnp.
Also aurelia 1 and aurelia 2 do not work with yarn pnp either.

You can try add a config to turn pnp off. https://github.com/aurelia/new/blob/master/common/.yarnrc.yml

I will add that file to dumber's skeleton.

**Comment by 3cp** [comment]
I added that line in. Please try again.

**Comment by 3cp** [comment]
It seems yarn also didn't support npm's override config.

https://github.com/dumberjs/new/blob/master/common/package.json#L132C3-L132C14

It still tris to install the normal chokidar v2.

**Comment by 3cp** [comment]
I used yarn and pnpm both long ago, and also contributed to them. But in the end, I came back to npm, because all the saving they provided did not justify the time I wasted to understand their difference with npm.

I only want to focus on my code, not the tool.

**Comment by simonfox** [comment]
@3cp thanks for looking into this...we've been using yarn1 for a long time and thought we would move back to npm as I thought I'd heard it was supposed to be much better than the early days...but we are running into an issue that seems to be covered by these...
https://github.com/npm/cli/issues/4028
https://github.com/npm/cli/issues/3208

`mkdir node_modules && npm ci` as suggested does help, but just wow 🤯 

I'm currently looking at pnpm, but sounds like I might be wasting my time?

Out of interest, are you on the latest npm? Those issues arose from v7 and are still in current stable...

**Comment by simonfox** [comment]
override config [is resolutions yarn](https://yarnpkg.com/configuration/manifest#resolutions)?

**Comment by 3cp** [comment]
Probably because I never push up lock file so never used "npm ci" in my ci :-)
The yarn "resolutions" does looks similar, it might be different. The example shows exact version number, I don't know whether it supports "^3.0.0" like npm overrides.

Another thing is npm install will install the version of your overrides, not the ones implicitly requires by some dependencies. I doubt "resolutions" does the same, I guess it only affects resolution, not the yarn install.

For pnpm, compatibility wise, I had better experience with it than yarn. It's fast, but the main selling point for me was the disk saving.

**Comment by simonfox** [comment]
I don't think you use typescript do you?

I have some strange ts build issues under pnpm where certain packages generate errors like `error TS2742: The inferred type of 'default' cannot be named without a reference to '.pnpm/reselect@4.1.7/node_modules/reselect'.`

I can resolve with `paths` config in `tsconfig`, but it's still a little unnerving.

**Comment by 3cp** [comment]
I use ts with npm. Didn't recall anything like that with pnpm before.

That's exactly the kind of trouble I hate spending time on :-)
