### ISSUE TITLE
TODO use mozilla/source-map SourceNode to drive code transform

### ISSUE THREAD

**Issue by 3cp** [dumberjs/dumber#6]
So all code transform will have full correct source map support.

**Comment by bigopon** [comment]
Why is this? Is this what everyone else is using?

**Comment by 3cp** [comment]
Dumber rewrites some code in order to support AMD. The source map support is cheap and not good.

SourceNode is the way to support source map for any compiler/transfomer work. It is actually quite easy to use, similar to concat-with-source-map.

**Comment by 3cp** [comment]
Reading rollup source code leads me to this intuitive tool https://github.com/Rich-Harris/magic-string

**Comment by 3cp** [comment]
Inspired by magic-string, https://github.com/dumberjs/modify-code
